### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchMethodError: processing.core.PVector.set(FF)V 	

### ISSUE THREAD

**Issue by dimpapadop** [genekogan/KinectProjectorToolkit#26]
Hallo.
SimpleOpenni 1.96
I am trying to run some of the examples but i keep taking the message
" java.lang.RuntimeException: java.lang.NoSuchMethodError: processing.core.PVector.set(FF)V
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:412)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: processing.core.PVector.set(FF)V
	at KinectProjectorToolkit.ProjectedContour.calculateProjectedContour(Unknown Source)
	at KinectProjectorToolkit.KinectProjectorToolkit.getProjectedContour(Unknown Source)
	at TestFallingPolygons.draw(TestFallingPolygons.java:78)
	at processing.core.PApplet.handleDraw(PApplet.java:2437)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:859)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505) "

No matter if i am on Processing 2 or 3.
For example i run the falling polygons example. I a user does not appear in front of the kinect everything is fine and polygons keep falling.
As soon as a user appears, the above message stops the sketch

thank you in advance
Dimitrios

**Comment by Gcostagliola** [comment]
I´ve the same issue here
